version: '3.3'

#
#services:
#  web:
#    build: ./
#    ports:
#      - "5000:5000"
#
#    env_file:
#      - ./.env
#  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=hello_django
#      - POSTGRES_PASSWORD=hello_django
#      - POSTGRES_DB=hello_django_dev
#volumes:
#  postgres_data:

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code/TestProj/
    ports:
      - "8000:8000"
    depends_on:
      - db
