version: '3.3'

#web:
#    container_name: web
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    networks:
#      - webnet
#      - nginx_network
#    expose:
#      - 8000
#    environment:
#      DATABASE_PORT: '5432'
#    env_file:
#      - ./.env
#    restart: on-failure
#    command: python manage.py runserver 0.0.0.0:8000
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/"]
#      interval: 1m
#      timeout: 5s
#      retries: 2

services:
  web:
    build: ./
    ports:
      - "5000:5000"
      
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data:
